<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="0" failures="2" skipped="0" tests="9" time="0.145" timestamp="2023-11-30T18:38:44.406005" hostname="LAPTOP-BKEQF5PU"><testcase classname="test_First" name="test_1" time="0.001" /><testcase classname="test_First" name="test_2" time="0.001" /><testcase classname="test_First" name="test_3" time="0.001"><failure message="AssertionError: Title does not match&#10;assert 'jenkins' in 'Jenkins in CI server'">def test_3():
        name='jenkins'
        title='Jenkins in CI server'
&gt;       assert name in title,"Title does not match"
E       AssertionError: Title does not match
E       assert 'jenkins' in 'Jenkins in CI server'

test_First.py:15: AssertionError</failure></testcase><testcase classname="test_Four" name="test_responsecode200" time="0.002" /><testcase classname="test_Four" name="test_responsecode400" time="0.001" /><testcase classname="test_Second" name="test_Login" time="0.001" /><testcase classname="test_Second" name="test_checkout" time="0.001" /><testcase classname="test_Second" name="test_logout" time="0.001" /><testcase classname="test_Three.MyTestCase" name="test_something" time="0.002"><failure message="AssertionError: True != False">self = &lt;test_Three.MyTestCase testMethod=test_something&gt;

    def test_something(self):
&gt;       self.assertEqual(True, False)  # add assertion here
E       AssertionError: True != False

test_Three.py:6: AssertionError</failure></testcase></testsuite></testsuites>